Feature/85 allow users to change their password via profile
yuremboo/UJP-Sport-Hub pull request #107
Opened 2022-09-15 14:31 UTC by pro100proger

2022-09-18 15:15 UTC, ostartt approved these changes

2022-09-19 13:38 UTC, yuremboo requested changes

2022-09-19 13:38 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/controller/UserController.java
> +    @PutMapping(path = "/change/password")
/password

2022-09-19 13:38 UTC, yuremboo commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto = update
validate

2022-09-19 13:38 UTC, yuremboo commented on src/test/java/com/softserve/edu/sporthubujp/service/impl/UserServiceImplTest.java
> +    void updateUser() {
nice tests :)))))

2022-09-19 13:41 UTC, pro100proger commented on src/test/java/com/softserve/edu/sporthubujp/service/impl/UserServiceImplTest.java
> +    void updateUser() {
It's preparation before testing)

2022-09-19 14:17 UTC, NastiaChaikovska approved these changes

2022-09-24 18:51 UTC, yuremboo requested changes

2022-09-24 18:51 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/controller/ArticleController.java
> +//        CompletableFuture.supplyAsync(() -> logRepository.save(new Logs(id)));
do not comment code

2022-09-24 18:51 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/service/UserService.java
> +    UserDTO updatePassword(User oldUser, UserSavePasswordDTO newUser) throws InvalidPropertiesFormatException;
this is not oldUser :)

2022-09-24 18:51 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/service/impl/UserServiceImpl.java
> +                throw new InvalidPropertiesFormatException("Service: password must contain at least 8 characters (letters and numbers)");
Use application based exception, like ServiceException etc.

2022-09-27 07:13 UTC, yuremboo approved these changes

2022-09-27 07:13 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/service/impl/UserServiceImpl.java
> +    //    @Override
remove commented code

2022-09-27 07:59 UTC, merged