create all entities
yuremboo/UJP-Sport-Hub pull request #39
Opened 2022-07-19 19:22 UTC by OksanaOlesja

based on DB designed schemas and connection to the database

2022-07-20 06:58 UTC, AndriyBarskyi requested changes
34-38 54-58 навіщо було видаляти початкову dependency драйвера постгресу і вставляти інший
63-74 чому видалено lombok
всі класи з ентіті занадто довгі, ми для цього як раз і добавляли lombok, можна прописати геттери, сеттери, equals, hashcode i toString за допомогою анотацій

2022-07-20 07:46 UTC, yuremboo requested changes

2022-07-20 07:46 UTC, yuremboo commented on pom.xml
> +        <dependency>
Remove h2database, we don't need it

2022-07-20 07:46 UTC, yuremboo commented on pom.xml
> +<!--            <plugin>-->
Uncomment it please

2022-07-20 07:46 UTC, yuremboo commented on src/main/java/entity/ArticleEntity.java
> +public class ArticleEntity {
Let's call all entities without suffix "Entity", just "Article" etc.

2022-07-20 07:46 UTC, yuremboo commented on src/main/java/entity/ArticleEntity.java
> +    @Column(name = "TEXT", length = 4000, nullable = false, unique = false)
I'm not sure if 4000 symbols are enough. Let's mark it:
@Column(columnDefinition="TEXT")

2022-07-20 07:46 UTC, yuremboo commented on src/main/java/entity/ArticleEntity.java
> +    @OneToOne(mappedBy = "comment_acticle")
Should be one to many, one article has many comments

2022-07-20 07:46 UTC, yuremboo commented on src/main/java/entity/ArticleEntity.java
> +    public UUID getId() {
Please, use lombok for getters and setters

2022-07-20 07:46 UTC, yuremboo commented on src/main/java/entity/ArticleEntity.java
> +    @Column(name = "TITLE", length = 255, nullable = false, unique = false)
Let's name column names in lower case

2022-07-20 07:46 UTC, yuremboo commented on src/main/java/entity/ArticleEntity.java
> +    private String category_id  ;
Should be a relation ManyToOne instead of id key

2022-07-20 07:46 UTC, yuremboo commented on src/main/java/entity/ArticleEntity.java
> +    private Timestamp create_date_time  ;
Add audit here like https://www.baeldung.com/database-auditing-jpa#spring

2022-07-20 07:46 UTC, yuremboo commented on src/main/resources/application.properties
> +spring.h2.console.enabled=true
we don't need h2

2022-07-20 07:46 UTC, yuremboo commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/SportHubUJP?createDatabaseIfNotExist=true
you can add the next lines to generate tables automatically and you will find out if your entities are valid:

```
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
```

2022-07-20 07:46 UTC, yuremboo commented on src/main/java/entity/CommentsEntity.java
> +    @OneToOne
Many to One

2022-07-20 18:29 UTC, OksanaOlesja commented on src/main/java/entity/CommentsEntity.java
> +    private String commenter_id   ;
this field is in our scheme
https://drive.google.com/file/d/1KbfnoPllrT76dejHlslATHSYHa46v4PC/view

2022-07-21 11:12 UTC, AndriyBarskyi commented on src/main/java/entity/Categories.java
> +    @Column(name="update_date_time",  nullable=false, unique=false)
update_date_time should be nullable

2022-07-21 19:50 UTC, yuremboo requested changes

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/Article.java
> +package com.example.sporthubujp.entity;
com.softserve.sporthubujp.entity

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/Article.java
> +    @Column(name="update_date_time",  nullable=false, unique=false)
nullable=true

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/Article.java
> +    private String categoryId  ;
remove this field

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/Category.java
> +    private String parentCategoriesId;
remove this field. Should be parent -> child relation:

```
@ManyToOne(fetch = FetchType.LAZY, optional=true)
@JoinColumn(name="parent_category_id")
private Category parent;

@OneToMany(mappedBy="parent", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval=true)
private Set<Category> children = new HashSet<>();
```

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/Comments.java
> +public class Comments {
Comment

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/Comments.java
> +    private String commenterId;
please, remove this field

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/Comments.java
> +    private String articleId;
please, remove this field

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/Subscription.java
> +    private String userId;
please, remove this field

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/Subscription.java
> +    private String teamId;
please, remove this field

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/Subscription.java
> +    private String categoryId;
please, remove this field

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/Team.java
> +    private String categoryId;
please, remove this field

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/Team.java
> +    private String subcategory;
please, remove this field

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/User.java
> +    private List<Comments> comment;
private List<Comments>  comments

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/Article.java
> +    private Timestamp createDateTime;
LocalDateTime

2022-07-21 19:50 UTC, yuremboo commented on src/main/java/com/example/sporthubujp/entity/Article.java
> +    private Timestamp updateDateTime;
LocalDateTime

2022-07-21 20:53 UTC, yuremboo approved these changes

2022-07-21 21:05 UTC, ostartt approved these changes

2022-07-21 21:05 UTC, ostartt approved these changes

2022-07-21 21:12 UTC, AndriyBarskyi requested changes

2022-07-21 21:12 UTC, AndriyBarskyi commented on src/main/java/com/softserve/edu/sporthubujp/entity/Comment.java
> +    private Integer dislikes  ;
Why are these attributes not annotated as columns?

2022-07-22 07:02 UTC, AndriyBarskyi approved these changes

2022-07-22 07:02 UTC, merged