Feature/16 liquibase maven integration
yuremboo/UJP-Sport-Hub pull request #41
Opened 2022-07-22 09:20 UTC by ostartt

mvn liquibase:update command executes correct

2022-07-22 10:43 UTC, yuremboo requested changes

2022-07-22 10:43 UTC, yuremboo commented on liquibase-outputChangeLog.xml
> +<?xml version="1.1" encoding="UTF-8" standalone="no"?>
please, remove this file

2022-07-22 10:43 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/entity/Article.java
> +@Data
Exclude all @OneToMany from equals and hashCode, because later you will get LazyInitializationException

2022-07-22 10:43 UTC, yuremboo commented on src/main/resources/application.properties
> +server.port=8081
lets use default 8080

2022-07-22 10:43 UTC, yuremboo commented on src/main/resources/db.changelog/liquibase-changeLog.xml
> +        <createTable tableName="teams">
table names should be in UPPERCASE

2022-07-22 10:43 UTC, yuremboo commented on src/main/resources/db.changelog/liquibase-changeLog.xml
> +        <addUniqueConstraint columnNames="name" constraintName="uk_a510no6sjwqcx153yd5sm4jrr" tableName="teams"/>
please, rename all such autogenerated constraints like uk_a510no6sjwqcx153yd5sm4jrr -> uk_name

2022-07-23 14:28 UTC, OksanaOlesja approved these changes

2022-07-24 17:36 UTC, AndriyBarskyi approved these changes

2022-07-25 08:31 UTC, yuremboo approved these changes

2022-07-25 08:32 UTC, merged