Feature/23 delete an existing article
yuremboo/UJP-Sport-Hub pull request #48
Opened 2022-08-01 12:41 UTC by OksanaOlesja

2022-08-01 15:00 UTC, yuremboo requested changes

2022-08-01 15:00 UTC, yuremboo commented on .env
> +JDBC_DATABASE_URL=postgres://vcdmbesbrqyrjw:b9089973cc5a5774e7bcd00e36aead6401132a64f7c47edef1c671253e3804eb@ec2-54-155-110-181.eu-west-1.compute.amazonaws.com:5432/df8129v9apku4p
please, remove this file

2022-08-01 15:00 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/service/impl/ArticleServiceImpl.java
> +        if (deleteArticleById == null)
if(!articleRepository.existsById(id)) {

2022-08-01 15:00 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/service/impl/ArticleServiceImpl.java
> +            //throw new articleServiceException(ErrorMessages.RECORD_NOT_FOUND.getErrorMessage());
You can create your exception and throw it here instead of commenting :)

2022-08-02 09:11 UTC, yuremboo requested changes

2022-08-02 09:11 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/controller/ArticleController.java
> +    public ResponseEntity<Void> deleteArticle(@PathVariable("id") String articleId)
Please, apply codestyle

2022-08-02 09:11 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/service/impl/ArticleServiceImpl.java
> +        articleRepository.delete(deleteArticleById);
use deleteById and you can remove line 34

2022-08-02 18:53 UTC, yuremboo approved these changes
Approved, but apply codestyle

2022-08-03 19:21 UTC, AndriyBarskyi approved these changes

2022-08-05 07:08 UTC, merged