Feature/31 allow users to sign up
yuremboo/UJP-Sport-Hub pull request #54
Opened 2022-08-05 07:27 UTC by ostartt

2022-08-09 07:13 UTC, yuremboo requested changes

2022-08-09 07:13 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/controller/ArticleController.java
> +    @PreAuthorize("hasAuthority('USER')")
article can read anybody

2022-08-09 07:13 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/entity/ConfirmationToken.java
> +    private Long id;
keep consistency with other tables, use UUID

2022-08-09 07:13 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/entity/ConfirmationToken.java
> +    @ManyToOne
@OneToOne ?

2022-08-09 07:13 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/repository/ConfirmationTokenRepository.java
> +@Transactional(readOnly = true)
@ Transactional required only on services

2022-08-09 07:13 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/repository/ConfirmationTokenRepository.java
> +    @Transactional
@ Transactional required only on services

2022-08-09 07:13 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/repository/UserRepository.java
> +@Transactional(readOnly = true)
Transactional required only on services

2022-08-09 07:13 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/service/impl/EmailServiceImpl.java
> +    private final static Logger LOGGER = LoggerFactory
you can use Lombok @ Slf4j

2022-08-09 07:13 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/service/impl/RegistrationService.java
> +        return "<div style=\"font-family:Helvetica,Arial,sans-serif;font-size:16px;margin:0;color:#0b0c0c\">\n" +
Use .html file in resources for this

2022-08-09 07:13 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/service/impl/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
Add logs

2022-08-10 08:07 UTC, yuremboo approved these changes

2022-08-10 08:09 UTC, AndriyBarskyi approved these changes

2022-08-10 09:06 UTC, merged