Feature/47 configure logging
yuremboo/UJP-Sport-Hub pull request #55
Opened 2022-08-08 08:26 UTC by OksanaOlesja

2022-08-08 17:30 UTC, AndriyBarskyi approved these changes

2022-08-09 07:15 UTC, yuremboo requested changes

2022-08-09 07:15 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/controller/ArticleController.java
> +    private static final Logger LOG = Logger.getLogger(ArticleController.class.getName());
you can use @ Slf4j annotation instead this line

2022-08-09 07:15 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/controller/ArticleController.java
> +        LOG.log(Level.INFO, "Get article by id {0}", id);
LOG.info("Get article by id {}", id);

2022-08-09 07:15 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/controller/ArticleController.java
> +        LOG.log(Level.INFO, "Delete article by id {0}", articleId);
the same

2022-08-09 07:15 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/service/impl/ArticleServiceImpl.java
> +            LOG.throwing(ArticleServiceImpl.class.getName(),"deleteArticleById",new ArticleServiceException("Record with provided id is not found"));
LOG.error(...)

2022-08-09 15:33 UTC, NastiaChaikovska approved these changes

2022-08-10 08:02 UTC, yuremboo approved these changes

2022-08-10 08:39 UTC, merged