Feature/get all articles
yuremboo/UJP-Sport-Hub pull request #57
Opened 2022-08-08 11:27 UTC by NastiaChaikovska

2022-08-09 07:21 UTC, yuremboo requested changes

2022-08-09 07:21 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/controller/CategoryController.java
> +    @PreAuthorize("hasAnyAuthority('ADMIN')")
It is not only for ADMIN its for everybody

2022-08-10 08:04 UTC, yuremboo approved these changes

2022-08-10 08:06 UTC, OksanaOlesja approved these changes

2022-08-10 08:19 UTC, merged