Feature/20 allow admin to edit an existing article
yuremboo/UJP-Sport-Hub pull request #58
Opened 2022-08-08 17:21 UTC by pro100proger

2022-08-08 17:35 UTC, AndriyBarskyi requested changes

2022-08-08 17:35 UTC, AndriyBarskyi commented on src/main/java/com/softserve/edu/sporthubujp/controller/ArticleController.java
> +    {
Code style

2022-08-08 17:35 UTC, AndriyBarskyi commented on src/main/resources/application.properties
> +spring.datasource.password=this1pass
Do not change properties

2022-08-08 18:56 UTC, AndriyBarskyi approved these changes

2022-08-08 19:16 UTC, ostartt approved these changes

2022-08-09 07:24 UTC, yuremboo requested changes

2022-08-09 07:24 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/entity/Article.java
> +@Table(name="ARTICLES")
Change in liquibase also

2022-08-10 08:07 UTC, yuremboo requested changes

2022-08-10 08:07 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/entity/Article.java
> +    @Column(name = "caption", length = 255, nullable = false, unique = false)
these changes should also go to liquibase

2022-08-10 08:07 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/service/impl/ArticleServiceImpl.java
> +            .map(article -> {
you can use MapStruct like:

`void update(@MappingTarger Article articleFromDb, Article newArticle);`

2022-08-11 11:43 UTC, ostartt approved these changes

2022-08-11 12:04 UTC, AndriyBarskyi approved these changes

2022-08-11 15:38 UTC, yuremboo requested changes

2022-08-11 15:38 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/controller/ArticleController.java
> +    @PreAuthorize("hasAnyAuthority('USER', 'ADMIN')")
only ADMIN can update article

2022-08-11 18:51 UTC, yuremboo approved these changes

2022-08-11 19:32 UTC, merged