Feature/84 allow users to update their personal information
yuremboo/UJP-Sport-Hub pull request #92
Opened 2022-08-23 14:42 UTC by pro100proger

2022-08-24 14:36 UTC, ostartt approved these changes

2022-08-26 08:44 UTC, yuremboo requested changes

2022-08-26 08:44 UTC, yuremboo commented on src/main/java/com/softserve/edu/sporthubujp/controller/UserController.java
> +        @PathVariable("id") String id) {
Do not pass id, you need to use Principal, because your user can update any other user info :)

2022-08-30 13:37 UTC, yuremboo approved these changes

2022-08-31 05:46 UTC, merged