made login return a response body
yuremboo/UJP-Sport-Hub pull request #93
Opened 2022-08-25 20:15 UTC by ostartt

2022-08-26 08:03 UTC, NastiaChaikovska approved these changes

2022-08-26 08:46 UTC, yuremboo requested changes

2022-08-26 08:46 UTC, yuremboo commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto = create-drop
validate

2022-08-28 14:20 UTC, pro100proger approved these changes

2022-08-29 07:51 UTC, yuremboo approved these changes

2022-08-29 07:56 UTC, merged